### ISSUE TITLE
invalid Syntax while importing the library

### ISSUE THREAD

**Issue by lucky630** [thoppe/greasepaint#1]
msg = f"{key} not in class {self}"
                                     ^
SyntaxError: invalid syntax

getting above error while importing the greasepaint library. i am using the python 2 environment.

**Comment by thoppe** [comment]
Sorry, greasepaint is python 3 only! That error comes from using the
g-strings which are a really useful python3 thing.

**Comment by lucky630** [comment]
yeah now its working in the python3

**Comment by thoppe** [comment]
Also, I meant f-strings not g-strings 😳
